language: android
jdk: oraclejdk7
sudo: false

notifications:
  # Slack notification on failure (secured token).
  slack:
    rooms:
      secure: sOTcwi1DT0lJykB/smJQwJ5lQblg9jc5PtLsTu4euI/P4nCv1CPu5DVZ1aDwXL6TPDUO5uEwbzbjVFZzrl2nFdAV9XvGT3wL3Zrm2Y5HBtwi8JWdbc4dYR/xobJlIg7HRczXwoFt6yls4BUayNJJbZFV9q0ftmUSe77Pag/ZWQw=
    on_failure: always
    on_success: change

android:
  components:
    - extra-android-m2repository
    - extra-android-support
    - build-tools-23.0.1
    - android-23

env:
  global:
    - GRADLE_OPTS="-XX:MaxPermSize=4g -Xmx4g"
    - ANDROID_SDKS=android-14
    - ANDROID_TARGET=android-14
    # WordPress.com Username
    - secure: "YChsdOlmprsul75Wp96y63eUp0ZFafM9f1Syi1S6d1AewfIvaJmWw+cq26vQPE8868KJfhLvSH2eQJ67/jR4agUs9Z4vWlD4zYV+PSA0l3dXh2LIkBaJ28ACdpvFmZzh/gZpcNLEyBu160K9afKx9TSc40eiQgHAYjTvqbnq7H4="
    # WordPress.com Password
    - secure: "JootE3YTPaKW6tbDBH0XdpjUUQxfSHQO5Ji3a1zfYRto4fttaNW8m3I7UJBQa62lWD+TorvsgFX6d2YrBIe6RS07Hn5kN/iblC7Eh7wXpvj8K24dZKboSeTXxkjOmbqpk9eQiQd32uUeXqCPzrZYpTYzBCbEjROGs+7OT0fN1QQ="
#    - secure: "lo8iKih1PpgvYJcz2aasrWGXNEv+9Nw0BpXrF9h8NwAKbd38+X8OSUvS+37jZrVC/X55qDLpfsbeLpdLBXM69NH/x5UkVdBbccxzxPRYfUWTwXzdav1CLRJpZOdDuDw+gWUmKfyxpdLGyXY5kK2Yh1mdSWa1P9y1O98WBR6VipE="
#              ^^ Wrong password to test failure
    # Test Object API Key
    - secure: "NyPP4x1Qn7dXNCUy+eHCchPfnfa3ymM9hISbHVwYh9QoAwEX2IVC4Axq2M9+DKbBWoFxY6ky1QNr4hSaXgoIuGod1pgWZMSJBCjFRPtqWyrvn13KvuAuzL3sTeyuCX60jXOFuLFGroYn4ckZ2r3Z3vEQQbY748JYKj8FoKDN0wU="
#    - "TESTOBJECT=1"
    - "SAUCE=1"

install:
  # Setup gradle.properties
  - cp WordPress/gradle.properties-example WordPress/gradle.properties

addons:
  sauce_connect:
    username: "srstancil"
    access_key:
      secure: "YFkTrLnL2yOUbhJK4a08AK9gLAk7WPCvu78MvnVv0W7XajLq+7/bdlQtME0MXz5OuvRFalF0Kv2sxZjLGmUi/EJ/zkVlECCWt9kBL4vxMjI7f4J/TiP9Q+QCuupfr1pFUXT6npcflR8LOPMxAzkdPbtZeC9/3qAu/VyrUPTkQfs="

before_script:
  - npm install

script:
  # Temporarily removing to speed up first hack at testing - ./gradlew -PdisablePreDex build
  - npm test
