language: android
jdk: oraclejdk7
sudo: false

notifications:
  # Slack notification on failure (secured token).
  slack:
    rooms:
      secure: sOTcwi1DT0lJykB/smJQwJ5lQblg9jc5PtLsTu4euI/P4nCv1CPu5DVZ1aDwXL6TPDUO5uEwbzbjVFZzrl2nFdAV9XvGT3wL3Zrm2Y5HBtwi8JWdbc4dYR/xobJlIg7HRczXwoFt6yls4BUayNJJbZFV9q0ftmUSe77Pag/ZWQw=
    on_failure: always
    on_success: change

android:
  components:
    - extra-android-m2repository
    - extra-android-support
    - build-tools-23.0.1
    - android-23

env:
  global:
    - GRADLE_OPTS="-XX:MaxPermSize=4g -Xmx4g"
    - ANDROID_SDKS=android-14
    - ANDROID_TARGET=android-14

install:
  # Setup gradle.properties
  - cp WordPress/gradle.properties-example WordPress/gradle.properties

addons:
  sauce_connect:
    username: "srstancil"
    access_key:
      secure: "YFkTrLnL2yOUbhJK4a08AK9gLAk7WPCvu78MvnVv0W7XajLq+7/bdlQtME0MXz5OuvRFalF0Kv2sxZjLGmUi/EJ/zkVlECCWt9kBL4vxMjI7f4J/TiP9Q+QCuupfr1pFUXT6npcflR8LOPMxAzkdPbtZeC9/3qAu/VyrUPTkQfs="

env:
  secure: "NKjJLUHGqq7m7KoH+yVZxvqDatBBFOac7h8TCVPl7igKynDsMJ6jq8db68i/6qVXORwO/7SFsoXScOkxzxuMG0HzyF2ZD3YjGM/hsnNMAZFdELsMvvQ5rUv4U/M/PCRzqV6sodK3aRTcqH+W2OdrRo992R/eipiUAf8dZmQsoJ4="
  secure: "DyK0OqOJaE2OZiJwUr2sbHSQZbC6vl7pXQZILNmpop2/NKpp5kln8uKFQbqgNkNCyQXX31SOYAHk2ud8NkrtzlEjzAe5psIDIzAfFdoguXqRRbnAfMJCivSfwfAE+hS44BBlG8zENeY0TOMEM6LPZlAn2C1RE4bljA26N6M6hSg="
  - "SAUCE=1"

before_script:
  - npm install

script:
  # Temporarily removing to speed up first hack at testing - ./gradlew -PdisablePreDex build
  - npm test
